# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

# pods生成framework而不是默认的静态库
use_frameworks!

target 'CPFExtensions' do

    platform :ios, '8.0'

    # 链式调用
    pod 'CPFChain'
end
